parallel: --halt returns 0..100. Passes testsuite.

diff --git a/testsuite/wanted-results/parallel-local-3s b/testsuite/wanted-results/parallel-local-3s
--- a/testsuite/wanted-results/parallel-local-3s
+++ b/testsuite/wanted-results/parallel-local-3s
@@ -13,19 +13,19 @@ echo '### Test --halt-on-error 0';   (echo "sleep 1;true"; echo "sleep 2;false";
 /bin/bash: non_exist: command not found
 echo '**'
 **
-echo '### Test --halt-on-error 1';   (echo "sleep 1;true"; echo "sleep 2;false";echo "sleep 3;true") | parallel -j10 --halt-on-error 1;   echo $?;   (echo "sleep 1;true"; echo "sleep 2;false";echo "sleep 3;true";echo "sleep 4; non_exist") | parallel -j10 --halt 1;   echo $?
+echo '### Test --halt-on-error 1';   (echo "sleep 1;true"; echo "sleep 2;false";echo "sleep 3;true") | parallel -j10 --halt-on-error 1;   echo $?;   (echo "sleep 1;true"; echo "sleep 2; non_exist";echo "sleep 3;true";echo "sleep 4; false") | parallel -j10 --halt 1;   echo $?
 ### Test --halt-on-error 1
 1
 127
 parallel: This job failed:
 sleep 2;false
 parallel: Starting no more jobs. Waiting for 1 jobs to finish.
-parallel: This job failed:
-sleep 2;false
-parallel: Starting no more jobs. Waiting for 2 jobs to finish.
 /bin/bash: non_exist: command not found
 parallel: This job failed:
-sleep 4; non_exist
+sleep 2; non_exist
+parallel: Starting no more jobs. Waiting for 2 jobs to finish.
+parallel: This job failed:
+sleep 4; false
 echo '**'
 **
 echo '### Test --halt-on-error 2';   (echo "sleep 1;true"; echo "sleep 2;false";echo "sleep 3;true") | parallel -j10 --halt-on-error 2;   echo $?;   (echo "sleep 1;true"; echo "sleep 2;false";echo "sleep 3;true";echo "sleep 4; non_exist") | parallel -j10 --halt 2;   echo $?
@@ -61,98 +61,98 @@ parallel: This job succeeded:
 sleep 2;true
 echo '**'
 **
-echo '### Test last dying print --halt-on-error 1';   (seq 0 8;echo 0; echo 9) | parallel -j10 -kq --halt 1 perl -e 'sleep $ARGV[0];print STDERR @ARGV,"\n"; exit shift';   echo exit code $?
-### Test last dying print --halt-on-error 1
-exit code 9
+echo '### Test first dying print --halt-on-error 1';   (echo 0; echo 3; seq 0 7;echo 0; echo 8) | parallel -j10 -kq --halt 1 perl -e 'sleep $ARGV[0];print STDERR @ARGV,"\n"; exit shift';   echo exit code $?
+### Test first dying print --halt-on-error 1
+exit code 1
 0
-1
 parallel: This job failed:
 perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ shift 1
 parallel: Starting no more jobs. Waiting for 8 jobs to finish.
-2
 parallel: This job failed:
 perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ shift 2
 parallel: Starting no more jobs. Waiting for 7 jobs to finish.
 3
+0
+1
+2
 parallel: This job failed:
 perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ shift 3
 parallel: Starting no more jobs. Waiting for 6 jobs to finish.
+3
+parallel: This job failed:
+perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ shift 3
+parallel: Starting no more jobs. Waiting for 5 jobs to finish.
 4
 parallel: This job failed:
 perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ shift 4
-parallel: Starting no more jobs. Waiting for 5 jobs to finish.
+parallel: Starting no more jobs. Waiting for 4 jobs to finish.
 5
 parallel: This job failed:
 perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ shift 5
-parallel: Starting no more jobs. Waiting for 4 jobs to finish.
+parallel: Starting no more jobs. Waiting for 3 jobs to finish.
 6
 parallel: This job failed:
 perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ shift 6
-parallel: Starting no more jobs. Waiting for 3 jobs to finish.
-7
-parallel: This job failed:
-perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ shift 7
 parallel: Starting no more jobs. Waiting for 2 jobs to finish.
-8
+7
 0
 parallel: This job failed:
-perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ shift 8
+perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ shift 7
 parallel: Starting no more jobs. Waiting for 1 jobs to finish.
-9
+8
 parallel: This job failed:
-perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ shift 9
-echo '### Test last dying print --halt-on-error 2';   (seq 0 8;echo 0; echo 9) | parallel -j10 -kq --halt 2 perl -e 'sleep $ARGV[0];print STDERR @ARGV,"\n"; exit shift';   echo exit code $?
+perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ shift 8
+echo '### Test last dying print --halt-on-error 2';   (echo 0; echo 3; seq 0 7;echo 0; echo 8) | parallel -j10 -kq --halt 2 perl -e 'sleep $ARGV[0];print STDERR @ARGV,"\n"; exit shift';   echo exit code $?
 ### Test last dying print --halt-on-error 2
 exit code 1
 0
-1
 parallel: This job failed:
 perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ shift 1
-echo '### Test last dying print --halt-on-error -1';   (seq 0 8;echo 0; echo 9) | parallel -j10 -kq --halt -1 perl -e 'sleep $ARGV[0];print STDERR @ARGV,"\n"; exit not shift';   echo exit code $?
+echo '### Test last dying print --halt-on-error -1';   (echo 0; echo 3; seq 0 7;echo 0; echo 8) | parallel -j10 -kq --halt -1 perl -e 'sleep $ARGV[0];print STDERR @ARGV,"\n"; exit not shift';   echo exit code $?
 ### Test last dying print --halt-on-error -1
 exit code 0
 0
-1
 parallel: This job succeeded:
 perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ not\ shift 1
 parallel: Starting no more jobs. Waiting for 8 jobs to finish.
-2
 parallel: This job succeeded:
 perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ not\ shift 2
 parallel: Starting no more jobs. Waiting for 7 jobs to finish.
 3
+0
+1
+2
 parallel: This job succeeded:
 perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ not\ shift 3
 parallel: Starting no more jobs. Waiting for 6 jobs to finish.
+3
+parallel: This job succeeded:
+perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ not\ shift 3
+parallel: Starting no more jobs. Waiting for 5 jobs to finish.
 4
 parallel: This job succeeded:
 perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ not\ shift 4
-parallel: Starting no more jobs. Waiting for 5 jobs to finish.
+parallel: Starting no more jobs. Waiting for 4 jobs to finish.
 5
 parallel: This job succeeded:
 perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ not\ shift 5
-parallel: Starting no more jobs. Waiting for 4 jobs to finish.
+parallel: Starting no more jobs. Waiting for 3 jobs to finish.
 6
 parallel: This job succeeded:
 perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ not\ shift 6
-parallel: Starting no more jobs. Waiting for 3 jobs to finish.
-7
-parallel: This job succeeded:
-perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ not\ shift 7
 parallel: Starting no more jobs. Waiting for 2 jobs to finish.
-8
+7
 0
 parallel: This job succeeded:
-perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ not\ shift 8
+perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ not\ shift 7
 parallel: Starting no more jobs. Waiting for 1 jobs to finish.
-9
+8
 parallel: This job succeeded:
-perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ not\ shift 9
-echo '### Test last dying print --halt-on-error -2';   (seq 0 8;echo 0; echo 9) | parallel -j10 -kq --halt -2 perl -e 'sleep $ARGV[0];print STDERR @ARGV,"\n"; exit not shift';   echo exit code $?
+perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ not\ shift 8
+echo '### Test last dying print --halt-on-error -2';   (echo 0; echo 3; seq 0 7;echo 0; echo 8) | parallel -j10 -kq --halt -2 perl -e 'sleep $ARGV[0];print STDERR @ARGV,"\n"; exit not shift';   echo exit code $?
 ### Test last dying print --halt-on-error -2
 exit code 0
 0
-1
 parallel: This job succeeded:
 perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ not\ shift 1
 echo '**'
@@ -161,45 +161,9 @@ testhalt() {   echo '### testhalt --halt '$1;   (yes 0 | head -n 10; seq 10) | s
 ### testhalt --halt now,fail=0
 parallel: This job failed:
 sleep 0.3; exit 1
-parallel: This job failed:
-sleep 0.6; exit 2
-parallel: This job failed:
-sleep 0.9; exit 3
-parallel: This job failed:
-sleep 1.2; exit 4
-parallel: This job failed:
-sleep 1.5; exit 5
-parallel: This job failed:
-sleep 1.8; exit 6
-parallel: This job failed:
-sleep 2.1; exit 7
-parallel: This job failed:
-sleep 2.4; exit 8
-parallel: This job failed:
-sleep 2.7; exit 9
-parallel: This job failed:
-sleep 3; exit 10
 0
 parallel: This job failed:
 sleep 0.3; exit 1
-parallel: This job failed:
-sleep 0.6; exit 2
-parallel: This job failed:
-sleep 0.9; exit 3
-parallel: This job failed:
-sleep 1.2; exit 4
-parallel: This job failed:
-sleep 1.5; exit 5
-parallel: This job failed:
-sleep 1.8; exit 6
-parallel: This job failed:
-sleep 2.1; exit 7
-parallel: This job failed:
-sleep 2.4; exit 8
-parallel: This job failed:
-sleep 2.7; exit 9
-parallel: This job failed:
-sleep 3; exit 10
 0
 ### testhalt --halt now,fail=1
 parallel: This job failed:
@@ -232,7 +196,7 @@ parallel: This job failed:
 sleep 1.5; exit 5
 parallel: This job failed:
 sleep 1.8; exit 6
-6
+30
 parallel: This job failed:
 sleep 0.3; exit 1
 parallel: This job failed:
@@ -241,7 +205,11 @@ parallel: This job failed:
 sleep 0.9; exit 3
 parallel: This job failed:
 sleep 1.2; exit 4
-4
+parallel: This job failed:
+sleep 1.5; exit 5
+parallel: This job failed:
+sleep 1.8; exit 6
+30
 ### testhalt --halt now,fail=70%
 parallel: This job failed:
 sleep 0.3; exit 1
@@ -263,7 +231,7 @@ parallel: This job failed:
 sleep 2.7; exit 9
 parallel: This job failed:
 sleep 3; exit 10
-0
+50
 parallel: This job failed:
 sleep 0.3; exit 1
 parallel: This job failed:
@@ -278,49 +246,37 @@ parallel: This job failed:
 sleep 1.8; exit 6
 parallel: This job failed:
 sleep 2.1; exit 7
-7
+parallel: This job failed:
+sleep 2.4; exit 8
+parallel: This job failed:
+sleep 2.7; exit 9
+parallel: This job failed:
+sleep 3; exit 10
+50
 ### testhalt --halt soon,fail=0
 parallel: This job failed:
 sleep 0.3; exit 1
+parallel: Starting no more jobs. Waiting for 3 jobs to finish.
 parallel: This job failed:
 sleep 0.6; exit 2
+parallel: Starting no more jobs. Waiting for 2 jobs to finish.
 parallel: This job failed:
 sleep 0.9; exit 3
+parallel: Starting no more jobs. Waiting for 1 jobs to finish.
 parallel: This job failed:
 sleep 1.2; exit 4
-parallel: This job failed:
-sleep 1.5; exit 5
-parallel: This job failed:
-sleep 1.8; exit 6
-parallel: This job failed:
-sleep 2.1; exit 7
-parallel: This job failed:
-sleep 2.4; exit 8
-parallel: This job failed:
-sleep 2.7; exit 9
-parallel: This job failed:
-sleep 3; exit 10
 0
 parallel: This job failed:
 sleep 0.3; exit 1
+parallel: Starting no more jobs. Waiting for 3 jobs to finish.
 parallel: This job failed:
 sleep 0.6; exit 2
+parallel: Starting no more jobs. Waiting for 2 jobs to finish.
 parallel: This job failed:
 sleep 0.9; exit 3
+parallel: Starting no more jobs. Waiting for 1 jobs to finish.
 parallel: This job failed:
 sleep 1.2; exit 4
-parallel: This job failed:
-sleep 1.5; exit 5
-parallel: This job failed:
-sleep 1.8; exit 6
-parallel: This job failed:
-sleep 2.1; exit 7
-parallel: This job failed:
-sleep 2.4; exit 8
-parallel: This job failed:
-sleep 2.7; exit 9
-parallel: This job failed:
-sleep 3; exit 10
 0
 ### testhalt --halt soon,fail=1
 parallel: This job failed:
@@ -334,7 +290,7 @@ sleep 0.9; exit 3
 parallel: Starting no more jobs. Waiting for 1 jobs to finish.
 parallel: This job failed:
 sleep 1.2; exit 4
-4
+1
 parallel: This job failed:
 sleep 0.3; exit 1
 parallel: Starting no more jobs. Waiting for 3 jobs to finish.
@@ -346,7 +302,7 @@ sleep 0.9; exit 3
 parallel: Starting no more jobs. Waiting for 1 jobs to finish.
 parallel: This job failed:
 sleep 1.2; exit 4
-4
+1
 ### testhalt --halt soon,fail=2
 parallel: This job failed:
 sleep 0.3; exit 1
@@ -361,7 +317,7 @@ sleep 1.2; exit 4
 parallel: Starting no more jobs. Waiting for 1 jobs to finish.
 parallel: This job failed:
 sleep 1.5; exit 5
-5
+2
 parallel: This job failed:
 sleep 0.3; exit 1
 parallel: This job failed:
@@ -375,7 +331,7 @@ sleep 1.2; exit 4
 parallel: Starting no more jobs. Waiting for 1 jobs to finish.
 parallel: This job failed:
 sleep 1.5; exit 5
-5
+2
 ### testhalt --halt soon,fail=30%
 parallel: This job failed:
 sleep 0.3; exit 1
@@ -398,7 +354,7 @@ sleep 2.4; exit 8
 parallel: Starting no more jobs. Waiting for 1 jobs to finish.
 parallel: This job failed:
 sleep 2.7; exit 9
-9
+30
 parallel: This job failed:
 sleep 0.3; exit 1
 parallel: This job failed:
@@ -407,16 +363,20 @@ parallel: This job failed:
 sleep 0.9; exit 3
 parallel: This job failed:
 sleep 1.2; exit 4
-parallel: Starting no more jobs. Waiting for 3 jobs to finish.
 parallel: This job failed:
 sleep 1.5; exit 5
-parallel: Starting no more jobs. Waiting for 2 jobs to finish.
 parallel: This job failed:
 sleep 1.8; exit 6
-parallel: Starting no more jobs. Waiting for 1 jobs to finish.
+parallel: Starting no more jobs. Waiting for 3 jobs to finish.
 parallel: This job failed:
 sleep 2.1; exit 7
-7
+parallel: Starting no more jobs. Waiting for 2 jobs to finish.
+parallel: This job failed:
+sleep 2.4; exit 8
+parallel: Starting no more jobs. Waiting for 1 jobs to finish.
+parallel: This job failed:
+sleep 2.7; exit 9
+30
 ### testhalt --halt soon,fail=70%
 parallel: This job failed:
 sleep 0.3; exit 1
@@ -438,7 +398,7 @@ parallel: This job failed:
 sleep 2.7; exit 9
 parallel: This job failed:
 sleep 3; exit 10
-0
+50
 parallel: This job failed:
 sleep 0.3; exit 1
 parallel: This job failed:
@@ -453,59 +413,20 @@ parallel: This job failed:
 sleep 1.8; exit 6
 parallel: This job failed:
 sleep 2.1; exit 7
-parallel: Starting no more jobs. Waiting for 3 jobs to finish.
 parallel: This job failed:
 sleep 2.4; exit 8
-parallel: Starting no more jobs. Waiting for 2 jobs to finish.
 parallel: This job failed:
 sleep 2.7; exit 9
-parallel: Starting no more jobs. Waiting for 1 jobs to finish.
 parallel: This job failed:
 sleep 3; exit 10
-10
+50
 ### testhalt --halt now,success=0
-parallel: This job succeeded:
-sleep 0; exit 0
-parallel: This job succeeded:
-sleep 0; exit 0
-parallel: This job succeeded:
-sleep 0; exit 0
-parallel: This job succeeded:
-sleep 0; exit 0
-parallel: This job succeeded:
-sleep 0; exit 0
-parallel: This job succeeded:
-sleep 0; exit 0
-parallel: This job succeeded:
-sleep 0; exit 0
-parallel: This job succeeded:
-sleep 0; exit 0
-parallel: This job succeeded:
-sleep 0; exit 0
 parallel: This job succeeded:
 sleep 0; exit 0
 0
 parallel: This job succeeded:
 sleep 0; exit 0
-parallel: This job succeeded:
-sleep 0; exit 0
-parallel: This job succeeded:
-sleep 0; exit 0
-parallel: This job succeeded:
-sleep 0; exit 0
-parallel: This job succeeded:
-sleep 0; exit 0
-parallel: This job succeeded:
-sleep 0; exit 0
-parallel: This job succeeded:
-sleep 0; exit 0
-parallel: This job succeeded:
-sleep 0; exit 0
-parallel: This job succeeded:
-sleep 0; exit 0
-parallel: This job succeeded:
-sleep 0; exit 0
-7
+0
 ### testhalt --halt now,success=1
 parallel: This job succeeded:
 sleep 0; exit 0
@@ -533,7 +454,15 @@ parallel: This job succeeded:
 sleep 0; exit 0
 parallel: This job succeeded:
 sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
 parallel: This job succeeded:
 sleep 0; exit 0
 parallel: This job succeeded:
@@ -552,7 +481,19 @@ parallel: This job succeeded:
 sleep 0; exit 0
 parallel: This job succeeded:
 sleep 0; exit 0
-0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+50
 parallel: This job succeeded:
 sleep 0; exit 0
 parallel: This job succeeded:
@@ -573,50 +514,24 @@ parallel: This job succeeded:
 sleep 0; exit 0
 parallel: This job succeeded:
 sleep 0; exit 0
-7
+50
 ### testhalt --halt soon,success=0
 parallel: This job succeeded:
 sleep 0; exit 0
+parallel: Starting no more jobs. Waiting for 3 jobs to finish.
 parallel: This job succeeded:
 sleep 0; exit 0
+parallel: Starting no more jobs. Waiting for 2 jobs to finish.
 parallel: This job succeeded:
 sleep 0; exit 0
-parallel: This job succeeded:
-sleep 0; exit 0
-parallel: This job succeeded:
-sleep 0; exit 0
-parallel: This job succeeded:
-sleep 0; exit 0
-parallel: This job succeeded:
-sleep 0; exit 0
-parallel: This job succeeded:
-sleep 0; exit 0
-parallel: This job succeeded:
-sleep 0; exit 0
+parallel: Starting no more jobs. Waiting for 1 jobs to finish.
 parallel: This job succeeded:
 sleep 0; exit 0
 0
 parallel: This job succeeded:
 sleep 0; exit 0
-parallel: This job succeeded:
-sleep 0; exit 0
-parallel: This job succeeded:
-sleep 0; exit 0
-parallel: This job succeeded:
-sleep 0; exit 0
-parallel: This job succeeded:
-sleep 0; exit 0
-parallel: This job succeeded:
-sleep 0; exit 0
-parallel: This job succeeded:
-sleep 0; exit 0
-parallel: This job succeeded:
-sleep 0; exit 0
-parallel: This job succeeded:
-sleep 0; exit 0
-parallel: This job succeeded:
-sleep 0; exit 0
-7
+parallel: Starting no more jobs. Waiting for 3 jobs to finish.
+0
 ### testhalt --halt soon,success=1
 parallel: This job succeeded:
 sleep 0; exit 0
@@ -664,6 +579,10 @@ parallel: This job succeeded:
 sleep 0; exit 0
 parallel: This job succeeded:
 sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
 parallel: Starting no more jobs. Waiting for 3 jobs to finish.
 parallel: This job succeeded:
 sleep 0; exit 0
@@ -674,6 +593,10 @@ parallel: Starting no more jobs. Waiting for 1 jobs to finish.
 parallel: This job succeeded:
 sleep 0; exit 0
 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
 parallel: This job succeeded:
 sleep 0; exit 0
 parallel: This job succeeded:
@@ -693,7 +616,19 @@ parallel: This job succeeded:
 sleep 0; exit 0
 parallel: This job succeeded:
 sleep 0; exit 0
-0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+50
 parallel: This job succeeded:
 sleep 0; exit 0
 parallel: This job succeeded:
@@ -714,7 +649,7 @@ parallel: This job succeeded:
 sleep 0; exit 0
 parallel: This job succeeded:
 sleep 0; exit 0
-7
+50
 echo '**'
 **
 echo '### Test slow arguments generation - https://savannah.gnu.org/bugs/?32834';   seq 1 3 | parallel -j1 "sleep 2; echo {}" | parallel -kj2 echo
