testsuite: more testing of --halt.

diff --git a/testsuite/wanted-results/parallel-local-3s b/testsuite/wanted-results/parallel-local-3s
--- a/testsuite/wanted-results/parallel-local-3s
+++ b/testsuite/wanted-results/parallel-local-3s
@@ -157,6 +157,566 @@ parallel: This job succeeded:
 perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ not\ shift 1
 echo '**'
 **
+testhalt() {   echo '### testhalt --halt '$1;   (yes 0 | head -n 10; seq 10) | stdout parallel -kj4 --halt $1 'sleep {= $_*=0.3 =}; exit {}'; echo $?;   (seq 10; yes 0 | head -n 10) | stdout parallel -kj4 --halt $1 'sleep {= $_*=0.3 =}; exit {}'; echo $?; }; export -f testhalt;   parallel -kj0 testhalt ::: now,fail=0 now,fail=1 now,fail=2 now,fail=30%  now,fail=70%     soon,fail=0 soon,fail=1 soon,fail=2 soon,fail=30% soon,fail=70%     now,success=0 now,success=1 now,success=2 now,success=30% now,success=70%     soon,success=0 soon,success=1 soon,success=2 soon,success=30% now,success=70%
+### testhalt --halt now,fail=0
+parallel: This job failed:
+sleep 0.3; exit 1
+parallel: This job failed:
+sleep 0.6; exit 2
+parallel: This job failed:
+sleep 0.9; exit 3
+parallel: This job failed:
+sleep 1.2; exit 4
+parallel: This job failed:
+sleep 1.5; exit 5
+parallel: This job failed:
+sleep 1.8; exit 6
+parallel: This job failed:
+sleep 2.1; exit 7
+parallel: This job failed:
+sleep 2.4; exit 8
+parallel: This job failed:
+sleep 2.7; exit 9
+parallel: This job failed:
+sleep 3; exit 10
+0
+parallel: This job failed:
+sleep 0.3; exit 1
+parallel: This job failed:
+sleep 0.6; exit 2
+parallel: This job failed:
+sleep 0.9; exit 3
+parallel: This job failed:
+sleep 1.2; exit 4
+parallel: This job failed:
+sleep 1.5; exit 5
+parallel: This job failed:
+sleep 1.8; exit 6
+parallel: This job failed:
+sleep 2.1; exit 7
+parallel: This job failed:
+sleep 2.4; exit 8
+parallel: This job failed:
+sleep 2.7; exit 9
+parallel: This job failed:
+sleep 3; exit 10
+0
+### testhalt --halt now,fail=1
+parallel: This job failed:
+sleep 0.3; exit 1
+1
+parallel: This job failed:
+sleep 0.3; exit 1
+1
+### testhalt --halt now,fail=2
+parallel: This job failed:
+sleep 0.3; exit 1
+parallel: This job failed:
+sleep 0.6; exit 2
+2
+parallel: This job failed:
+sleep 0.3; exit 1
+parallel: This job failed:
+sleep 0.6; exit 2
+2
+### testhalt --halt now,fail=30%
+parallel: This job failed:
+sleep 0.3; exit 1
+parallel: This job failed:
+sleep 0.6; exit 2
+parallel: This job failed:
+sleep 0.9; exit 3
+parallel: This job failed:
+sleep 1.2; exit 4
+parallel: This job failed:
+sleep 1.5; exit 5
+parallel: This job failed:
+sleep 1.8; exit 6
+6
+parallel: This job failed:
+sleep 0.3; exit 1
+parallel: This job failed:
+sleep 0.6; exit 2
+parallel: This job failed:
+sleep 0.9; exit 3
+parallel: This job failed:
+sleep 1.2; exit 4
+4
+### testhalt --halt now,fail=70%
+parallel: This job failed:
+sleep 0.3; exit 1
+parallel: This job failed:
+sleep 0.6; exit 2
+parallel: This job failed:
+sleep 0.9; exit 3
+parallel: This job failed:
+sleep 1.2; exit 4
+parallel: This job failed:
+sleep 1.5; exit 5
+parallel: This job failed:
+sleep 1.8; exit 6
+parallel: This job failed:
+sleep 2.1; exit 7
+parallel: This job failed:
+sleep 2.4; exit 8
+parallel: This job failed:
+sleep 2.7; exit 9
+parallel: This job failed:
+sleep 3; exit 10
+0
+parallel: This job failed:
+sleep 0.3; exit 1
+parallel: This job failed:
+sleep 0.6; exit 2
+parallel: This job failed:
+sleep 0.9; exit 3
+parallel: This job failed:
+sleep 1.2; exit 4
+parallel: This job failed:
+sleep 1.5; exit 5
+parallel: This job failed:
+sleep 1.8; exit 6
+parallel: This job failed:
+sleep 2.1; exit 7
+7
+### testhalt --halt soon,fail=0
+parallel: This job failed:
+sleep 0.3; exit 1
+parallel: This job failed:
+sleep 0.6; exit 2
+parallel: This job failed:
+sleep 0.9; exit 3
+parallel: This job failed:
+sleep 1.2; exit 4
+parallel: This job failed:
+sleep 1.5; exit 5
+parallel: This job failed:
+sleep 1.8; exit 6
+parallel: This job failed:
+sleep 2.1; exit 7
+parallel: This job failed:
+sleep 2.4; exit 8
+parallel: This job failed:
+sleep 2.7; exit 9
+parallel: This job failed:
+sleep 3; exit 10
+0
+parallel: This job failed:
+sleep 0.3; exit 1
+parallel: This job failed:
+sleep 0.6; exit 2
+parallel: This job failed:
+sleep 0.9; exit 3
+parallel: This job failed:
+sleep 1.2; exit 4
+parallel: This job failed:
+sleep 1.5; exit 5
+parallel: This job failed:
+sleep 1.8; exit 6
+parallel: This job failed:
+sleep 2.1; exit 7
+parallel: This job failed:
+sleep 2.4; exit 8
+parallel: This job failed:
+sleep 2.7; exit 9
+parallel: This job failed:
+sleep 3; exit 10
+0
+### testhalt --halt soon,fail=1
+parallel: This job failed:
+sleep 0.3; exit 1
+parallel: Starting no more jobs. Waiting for 3 jobs to finish.
+parallel: This job failed:
+sleep 0.6; exit 2
+parallel: Starting no more jobs. Waiting for 2 jobs to finish.
+parallel: This job failed:
+sleep 0.9; exit 3
+parallel: Starting no more jobs. Waiting for 1 jobs to finish.
+parallel: This job failed:
+sleep 1.2; exit 4
+4
+parallel: This job failed:
+sleep 0.3; exit 1
+parallel: Starting no more jobs. Waiting for 3 jobs to finish.
+parallel: This job failed:
+sleep 0.6; exit 2
+parallel: Starting no more jobs. Waiting for 2 jobs to finish.
+parallel: This job failed:
+sleep 0.9; exit 3
+parallel: Starting no more jobs. Waiting for 1 jobs to finish.
+parallel: This job failed:
+sleep 1.2; exit 4
+4
+### testhalt --halt soon,fail=2
+parallel: This job failed:
+sleep 0.3; exit 1
+parallel: This job failed:
+sleep 0.6; exit 2
+parallel: Starting no more jobs. Waiting for 3 jobs to finish.
+parallel: This job failed:
+sleep 0.9; exit 3
+parallel: Starting no more jobs. Waiting for 2 jobs to finish.
+parallel: This job failed:
+sleep 1.2; exit 4
+parallel: Starting no more jobs. Waiting for 1 jobs to finish.
+parallel: This job failed:
+sleep 1.5; exit 5
+5
+parallel: This job failed:
+sleep 0.3; exit 1
+parallel: This job failed:
+sleep 0.6; exit 2
+parallel: Starting no more jobs. Waiting for 3 jobs to finish.
+parallel: This job failed:
+sleep 0.9; exit 3
+parallel: Starting no more jobs. Waiting for 2 jobs to finish.
+parallel: This job failed:
+sleep 1.2; exit 4
+parallel: Starting no more jobs. Waiting for 1 jobs to finish.
+parallel: This job failed:
+sleep 1.5; exit 5
+5
+### testhalt --halt soon,fail=30%
+parallel: This job failed:
+sleep 0.3; exit 1
+parallel: This job failed:
+sleep 0.6; exit 2
+parallel: This job failed:
+sleep 0.9; exit 3
+parallel: This job failed:
+sleep 1.2; exit 4
+parallel: This job failed:
+sleep 1.5; exit 5
+parallel: This job failed:
+sleep 1.8; exit 6
+parallel: Starting no more jobs. Waiting for 3 jobs to finish.
+parallel: This job failed:
+sleep 2.1; exit 7
+parallel: Starting no more jobs. Waiting for 2 jobs to finish.
+parallel: This job failed:
+sleep 2.4; exit 8
+parallel: Starting no more jobs. Waiting for 1 jobs to finish.
+parallel: This job failed:
+sleep 2.7; exit 9
+9
+parallel: This job failed:
+sleep 0.3; exit 1
+parallel: This job failed:
+sleep 0.6; exit 2
+parallel: This job failed:
+sleep 0.9; exit 3
+parallel: This job failed:
+sleep 1.2; exit 4
+parallel: Starting no more jobs. Waiting for 3 jobs to finish.
+parallel: This job failed:
+sleep 1.5; exit 5
+parallel: Starting no more jobs. Waiting for 2 jobs to finish.
+parallel: This job failed:
+sleep 1.8; exit 6
+parallel: Starting no more jobs. Waiting for 1 jobs to finish.
+parallel: This job failed:
+sleep 2.1; exit 7
+7
+### testhalt --halt soon,fail=70%
+parallel: This job failed:
+sleep 0.3; exit 1
+parallel: This job failed:
+sleep 0.6; exit 2
+parallel: This job failed:
+sleep 0.9; exit 3
+parallel: This job failed:
+sleep 1.2; exit 4
+parallel: This job failed:
+sleep 1.5; exit 5
+parallel: This job failed:
+sleep 1.8; exit 6
+parallel: This job failed:
+sleep 2.1; exit 7
+parallel: This job failed:
+sleep 2.4; exit 8
+parallel: This job failed:
+sleep 2.7; exit 9
+parallel: This job failed:
+sleep 3; exit 10
+0
+parallel: This job failed:
+sleep 0.3; exit 1
+parallel: This job failed:
+sleep 0.6; exit 2
+parallel: This job failed:
+sleep 0.9; exit 3
+parallel: This job failed:
+sleep 1.2; exit 4
+parallel: This job failed:
+sleep 1.5; exit 5
+parallel: This job failed:
+sleep 1.8; exit 6
+parallel: This job failed:
+sleep 2.1; exit 7
+parallel: Starting no more jobs. Waiting for 3 jobs to finish.
+parallel: This job failed:
+sleep 2.4; exit 8
+parallel: Starting no more jobs. Waiting for 2 jobs to finish.
+parallel: This job failed:
+sleep 2.7; exit 9
+parallel: Starting no more jobs. Waiting for 1 jobs to finish.
+parallel: This job failed:
+sleep 3; exit 10
+10
+### testhalt --halt now,success=0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+7
+### testhalt --halt now,success=1
+parallel: This job succeeded:
+sleep 0; exit 0
+0
+parallel: This job succeeded:
+sleep 0; exit 0
+0
+### testhalt --halt now,success=2
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+0
+### testhalt --halt now,success=30%
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+0
+### testhalt --halt now,success=70%
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+7
+### testhalt --halt soon,success=0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+7
+### testhalt --halt soon,success=1
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: Starting no more jobs. Waiting for 3 jobs to finish.
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: Starting no more jobs. Waiting for 2 jobs to finish.
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: Starting no more jobs. Waiting for 1 jobs to finish.
+parallel: This job succeeded:
+sleep 0; exit 0
+0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: Starting no more jobs. Waiting for 3 jobs to finish.
+0
+### testhalt --halt soon,success=2
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: Starting no more jobs. Waiting for 3 jobs to finish.
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: Starting no more jobs. Waiting for 2 jobs to finish.
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: Starting no more jobs. Waiting for 1 jobs to finish.
+parallel: This job succeeded:
+sleep 0; exit 0
+0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: Starting no more jobs. Waiting for 3 jobs to finish.
+0
+### testhalt --halt soon,success=30%
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: Starting no more jobs. Waiting for 3 jobs to finish.
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: Starting no more jobs. Waiting for 2 jobs to finish.
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: Starting no more jobs. Waiting for 1 jobs to finish.
+parallel: This job succeeded:
+sleep 0; exit 0
+0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: Starting no more jobs. Waiting for 3 jobs to finish.
+0
+### testhalt --halt now,success=70%
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+parallel: This job succeeded:
+sleep 0; exit 0
+7
+echo '**'
+**
 echo '### Test slow arguments generation - https://savannah.gnu.org/bugs/?32834';   seq 1 3 | parallel -j1 "sleep 2; echo {}" | parallel -kj2 echo
 ### Test slow arguments generation - https://savannah.gnu.org/bugs/?32834
 1
@@ -166,7 +726,7 @@ echo '**'
 **
 echo '### Are children killed if GNU Parallel receives TERM twice? There should be no sleep at the end'
 ### Are children killed if GNU Parallel receives TERM twice? There should be no sleep at the end
-  parallel -q bash -c 'sleep 120 & pid=$!; wait $pid' ::: 1 &     T=$!;     sleep 1;     pstree $$;     kill -TERM $T;     sleep 1;     pstree $$;     kill -TERM $T;     sleep 1;     pstree $$; echo '**'
+  parallel -q bash -c 'sleep 120 & pid=$!; wait $pid' ::: 1 &     T=$!;     sleep 2;     pstree $$;     kill -TERM $T;     sleep 1;     pstree $$;     kill -TERM $T;     sleep 1;     pstree $$; echo '**'
 bash-+-perl---bash---sleep
      `-pstree
 bash-+-perl---bash---sleep
@@ -178,7 +738,7 @@ parallel: Waiting for these 1 jobs to finish. Send SIGTERM again to stop now.
 parallel: bash -c sleep\ 120\ \&\ pid=\$\!\;\ wait\ \$pid 1
 echo '### Are children killed if GNU Parallel receives INT twice? There should be no sleep at the end'
 ### Are children killed if GNU Parallel receives INT twice? There should be no sleep at the end
-  parallel -q bash -c 'sleep 120 & pid=$!; wait $pid' ::: 1 &     T=$!;     sleep 1;     pstree $$;     kill -INT $T;     sleep 1;     pstree $$; 
+  parallel -q bash -c 'sleep 120 & pid=$!; wait $pid' ::: 1 &     T=$!;     sleep 2;     pstree $$;     kill -INT $T;     sleep 1;     pstree $$; 
 bash-+-perl---bash---sleep
      `-pstree
 bash---pstree
