parallel: killall will kill the family, too.

diff --git a/testsuite/wanted-results/parallel-local-3s b/testsuite/wanted-results/parallel-local-3s
--- a/testsuite/wanted-results/parallel-local-3s
+++ b/testsuite/wanted-results/parallel-local-3s
@@ -157,498 +157,515 @@ parallel: This job succeeded:
 perl -e sleep\ \$ARGV\[0\]\;print\ STDERR\ @ARGV,\"\\n\"\;\ exit\ not\ shift 1
 echo '**'
 **
-testhalt() {   echo '### testhalt --halt '$1;   (yes 0 | head -n 10; seq 10) | stdout parallel -kj4 --halt $1 'sleep {= $_*=0.3 =}; exit {}'; echo $?;   (seq 10; yes 0 | head -n 10) | stdout parallel -kj4 --halt $1 'sleep {= $_*=0.3 =}; exit {}'; echo $?; }; export -f testhalt;   parallel -kj0 testhalt ::: now,fail=0 now,fail=1 now,fail=2 now,fail=30%  now,fail=70%     soon,fail=0 soon,fail=1 soon,fail=2 soon,fail=30% soon,fail=70%     now,success=0 now,success=1 now,success=2 now,success=30% now,success=70%     soon,success=0 soon,success=1 soon,success=2 soon,success=30% now,success=70%
+testhalt() {   echo '### testhalt --halt '$1;   (yes 0 | head -n 10; seq 10) | stdout parallel -kj4 --halt $1 'sleep {= $_=$_*0.3+1 =}; exit {}'; echo $?;   (seq 10; yes 0 | head -n 10) | stdout parallel -kj4 --halt $1 'sleep {= $_=$_*0.3+1 =}; exit {}'; echo $?; }; export -f testhalt;   parallel -kj0 testhalt ::: now,fail=0 now,fail=1 now,fail=2 now,fail=30%  now,fail=70%     soon,fail=0 soon,fail=1 soon,fail=2 soon,fail=30% soon,fail=70%     now,success=0 now,success=1 now,success=2 now,success=30% now,success=70%     soon,success=0 soon,success=1 soon,success=2 soon,success=30% now,success=70%
 ### testhalt --halt now,fail=0
 parallel: This job failed:
-sleep 0.3; exit 1
+sleep 1.3; exit 1
 0
 parallel: This job failed:
-sleep 0.3; exit 1
+sleep 1.3; exit 1
 0
 ### testhalt --halt now,fail=1
 parallel: This job failed:
-sleep 0.3; exit 1
+sleep 1.3; exit 1
 1
 parallel: This job failed:
-sleep 0.3; exit 1
+sleep 1.3; exit 1
 1
 ### testhalt --halt now,fail=2
 parallel: This job failed:
-sleep 0.3; exit 1
+sleep 1.3; exit 1
 parallel: This job failed:
-sleep 0.6; exit 2
+sleep 1.6; exit 2
 2
 parallel: This job failed:
-sleep 0.3; exit 1
+sleep 1.3; exit 1
 parallel: This job failed:
-sleep 0.6; exit 2
+sleep 1.6; exit 2
 2
 ### testhalt --halt now,fail=30%
 parallel: This job failed:
-sleep 0.3; exit 1
+sleep 1.3; exit 1
 parallel: This job failed:
-sleep 0.6; exit 2
+sleep 1.6; exit 2
 parallel: This job failed:
-sleep 0.9; exit 3
+sleep 1.9; exit 3
 parallel: This job failed:
-sleep 1.2; exit 4
+sleep 2.2; exit 4
 parallel: This job failed:
-sleep 1.5; exit 5
+sleep 2.5; exit 5
 parallel: This job failed:
-sleep 1.8; exit 6
+sleep 2.8; exit 6
 30
 parallel: This job failed:
-sleep 0.3; exit 1
+sleep 1.3; exit 1
 parallel: This job failed:
-sleep 0.6; exit 2
+sleep 1.6; exit 2
 parallel: This job failed:
-sleep 0.9; exit 3
+sleep 1.9; exit 3
 parallel: This job failed:
-sleep 1.2; exit 4
+sleep 2.2; exit 4
 parallel: This job failed:
-sleep 1.5; exit 5
+sleep 2.5; exit 5
 parallel: This job failed:
-sleep 1.8; exit 6
+sleep 2.8; exit 6
 30
 ### testhalt --halt now,fail=70%
 parallel: This job failed:
-sleep 0.3; exit 1
+sleep 1.3; exit 1
 parallel: This job failed:
-sleep 0.6; exit 2
+sleep 1.6; exit 2
 parallel: This job failed:
-sleep 0.9; exit 3
+sleep 1.9; exit 3
 parallel: This job failed:
-sleep 1.2; exit 4
+sleep 2.2; exit 4
 parallel: This job failed:
-sleep 1.5; exit 5
+sleep 2.5; exit 5
 parallel: This job failed:
-sleep 1.8; exit 6
+sleep 2.8; exit 6
 parallel: This job failed:
-sleep 2.1; exit 7
+sleep 3.1; exit 7
 parallel: This job failed:
-sleep 2.4; exit 8
+sleep 3.4; exit 8
 parallel: This job failed:
-sleep 2.7; exit 9
+sleep 3.7; exit 9
 parallel: This job failed:
-sleep 3; exit 10
+sleep 4; exit 10
 50
 parallel: This job failed:
-sleep 0.3; exit 1
+sleep 1.3; exit 1
 parallel: This job failed:
-sleep 0.6; exit 2
+sleep 1.6; exit 2
 parallel: This job failed:
-sleep 0.9; exit 3
+sleep 1.9; exit 3
 parallel: This job failed:
-sleep 1.2; exit 4
+sleep 2.2; exit 4
 parallel: This job failed:
-sleep 1.5; exit 5
+sleep 2.5; exit 5
 parallel: This job failed:
-sleep 1.8; exit 6
+sleep 2.8; exit 6
 parallel: This job failed:
-sleep 2.1; exit 7
+sleep 3.1; exit 7
 parallel: This job failed:
-sleep 2.4; exit 8
+sleep 3.4; exit 8
 parallel: This job failed:
-sleep 2.7; exit 9
+sleep 3.7; exit 9
 parallel: This job failed:
-sleep 3; exit 10
+sleep 4; exit 10
 50
 ### testhalt --halt soon,fail=0
 parallel: This job failed:
-sleep 0.3; exit 1
+sleep 1.3; exit 1
 parallel: Starting no more jobs. Waiting for 3 jobs to finish.
 parallel: This job failed:
-sleep 0.6; exit 2
+sleep 1.6; exit 2
 parallel: Starting no more jobs. Waiting for 2 jobs to finish.
 parallel: This job failed:
-sleep 0.9; exit 3
+sleep 1.9; exit 3
 parallel: Starting no more jobs. Waiting for 1 jobs to finish.
 parallel: This job failed:
-sleep 1.2; exit 4
+sleep 2.2; exit 4
 0
 parallel: This job failed:
-sleep 0.3; exit 1
+sleep 1.3; exit 1
 parallel: Starting no more jobs. Waiting for 3 jobs to finish.
 parallel: This job failed:
-sleep 0.6; exit 2
+sleep 1.6; exit 2
 parallel: Starting no more jobs. Waiting for 2 jobs to finish.
 parallel: This job failed:
-sleep 0.9; exit 3
+sleep 1.9; exit 3
 parallel: Starting no more jobs. Waiting for 1 jobs to finish.
 parallel: This job failed:
-sleep 1.2; exit 4
+sleep 2.2; exit 4
 0
 ### testhalt --halt soon,fail=1
 parallel: This job failed:
-sleep 0.3; exit 1
+sleep 1.3; exit 1
 parallel: Starting no more jobs. Waiting for 3 jobs to finish.
 parallel: This job failed:
-sleep 0.6; exit 2
+sleep 1.6; exit 2
 parallel: Starting no more jobs. Waiting for 2 jobs to finish.
 parallel: This job failed:
-sleep 0.9; exit 3
+sleep 1.9; exit 3
 parallel: Starting no more jobs. Waiting for 1 jobs to finish.
 parallel: This job failed:
-sleep 1.2; exit 4
+sleep 2.2; exit 4
 1
 parallel: This job failed:
-sleep 0.3; exit 1
+sleep 1.3; exit 1
 parallel: Starting no more jobs. Waiting for 3 jobs to finish.
 parallel: This job failed:
-sleep 0.6; exit 2
+sleep 1.6; exit 2
 parallel: Starting no more jobs. Waiting for 2 jobs to finish.
 parallel: This job failed:
-sleep 0.9; exit 3
+sleep 1.9; exit 3
 parallel: Starting no more jobs. Waiting for 1 jobs to finish.
 parallel: This job failed:
-sleep 1.2; exit 4
+sleep 2.2; exit 4
 1
 ### testhalt --halt soon,fail=2
 parallel: This job failed:
-sleep 0.3; exit 1
+sleep 1.3; exit 1
 parallel: This job failed:
-sleep 0.6; exit 2
+sleep 1.6; exit 2
 parallel: Starting no more jobs. Waiting for 3 jobs to finish.
 parallel: This job failed:
-sleep 0.9; exit 3
+sleep 1.9; exit 3
 parallel: Starting no more jobs. Waiting for 2 jobs to finish.
 parallel: This job failed:
-sleep 1.2; exit 4
+sleep 2.2; exit 4
 parallel: Starting no more jobs. Waiting for 1 jobs to finish.
 parallel: This job failed:
-sleep 1.5; exit 5
+sleep 2.5; exit 5
 2
 parallel: This job failed:
-sleep 0.3; exit 1
+sleep 1.3; exit 1
 parallel: This job failed:
-sleep 0.6; exit 2
+sleep 1.6; exit 2
 parallel: Starting no more jobs. Waiting for 3 jobs to finish.
 parallel: This job failed:
-sleep 0.9; exit 3
+sleep 1.9; exit 3
 parallel: Starting no more jobs. Waiting for 2 jobs to finish.
 parallel: This job failed:
-sleep 1.2; exit 4
+sleep 2.2; exit 4
 parallel: Starting no more jobs. Waiting for 1 jobs to finish.
 parallel: This job failed:
-sleep 1.5; exit 5
+sleep 2.5; exit 5
 2
 ### testhalt --halt soon,fail=30%
 parallel: This job failed:
-sleep 0.3; exit 1
+sleep 1.3; exit 1
 parallel: This job failed:
-sleep 0.6; exit 2
+sleep 1.6; exit 2
 parallel: This job failed:
-sleep 0.9; exit 3
+sleep 1.9; exit 3
 parallel: This job failed:
-sleep 1.2; exit 4
+sleep 2.2; exit 4
 parallel: This job failed:
-sleep 1.5; exit 5
+sleep 2.5; exit 5
 parallel: This job failed:
-sleep 1.8; exit 6
+sleep 2.8; exit 6
 parallel: Starting no more jobs. Waiting for 3 jobs to finish.
 parallel: This job failed:
-sleep 2.1; exit 7
+sleep 3.1; exit 7
 parallel: Starting no more jobs. Waiting for 2 jobs to finish.
 parallel: This job failed:
-sleep 2.4; exit 8
+sleep 3.4; exit 8
 parallel: Starting no more jobs. Waiting for 1 jobs to finish.
 parallel: This job failed:
-sleep 2.7; exit 9
+sleep 3.7; exit 9
 30
 parallel: This job failed:
-sleep 0.3; exit 1
+sleep 1.3; exit 1
 parallel: This job failed:
-sleep 0.6; exit 2
+sleep 1.6; exit 2
 parallel: This job failed:
-sleep 0.9; exit 3
+sleep 1.9; exit 3
 parallel: This job failed:
-sleep 1.2; exit 4
+sleep 2.2; exit 4
 parallel: This job failed:
-sleep 1.5; exit 5
+sleep 2.5; exit 5
 parallel: This job failed:
-sleep 1.8; exit 6
+sleep 2.8; exit 6
 parallel: Starting no more jobs. Waiting for 3 jobs to finish.
 parallel: This job failed:
-sleep 2.1; exit 7
+sleep 3.1; exit 7
 parallel: Starting no more jobs. Waiting for 2 jobs to finish.
 parallel: This job failed:
-sleep 2.4; exit 8
+sleep 3.4; exit 8
 parallel: Starting no more jobs. Waiting for 1 jobs to finish.
 parallel: This job failed:
-sleep 2.7; exit 9
+sleep 3.7; exit 9
 30
 ### testhalt --halt soon,fail=70%
 parallel: This job failed:
-sleep 0.3; exit 1
+sleep 1.3; exit 1
 parallel: This job failed:
-sleep 0.6; exit 2
+sleep 1.6; exit 2
 parallel: This job failed:
-sleep 0.9; exit 3
+sleep 1.9; exit 3
 parallel: This job failed:
-sleep 1.2; exit 4
+sleep 2.2; exit 4
 parallel: This job failed:
-sleep 1.5; exit 5
+sleep 2.5; exit 5
 parallel: This job failed:
-sleep 1.8; exit 6
+sleep 2.8; exit 6
 parallel: This job failed:
-sleep 2.1; exit 7
+sleep 3.1; exit 7
 parallel: This job failed:
-sleep 2.4; exit 8
+sleep 3.4; exit 8
 parallel: This job failed:
-sleep 2.7; exit 9
+sleep 3.7; exit 9
 parallel: This job failed:
-sleep 3; exit 10
+sleep 4; exit 10
 50
 parallel: This job failed:
-sleep 0.3; exit 1
+sleep 1.3; exit 1
 parallel: This job failed:
-sleep 0.6; exit 2
+sleep 1.6; exit 2
 parallel: This job failed:
-sleep 0.9; exit 3
+sleep 1.9; exit 3
 parallel: This job failed:
-sleep 1.2; exit 4
+sleep 2.2; exit 4
 parallel: This job failed:
-sleep 1.5; exit 5
+sleep 2.5; exit 5
 parallel: This job failed:
-sleep 1.8; exit 6
+sleep 2.8; exit 6
 parallel: This job failed:
-sleep 2.1; exit 7
+sleep 3.1; exit 7
 parallel: This job failed:
-sleep 2.4; exit 8
+sleep 3.4; exit 8
 parallel: This job failed:
-sleep 2.7; exit 9
+sleep 3.7; exit 9
 parallel: This job failed:
-sleep 3; exit 10
+sleep 4; exit 10
 50
 ### testhalt --halt now,success=0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 0
 ### testhalt --halt now,success=1
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 0
 ### testhalt --halt now,success=2
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 0
 ### testhalt --halt now,success=30%
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 0
 ### testhalt --halt now,success=70%
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 50
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 50
 ### testhalt --halt soon,success=0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: Starting no more jobs. Waiting for 3 jobs to finish.
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: Starting no more jobs. Waiting for 2 jobs to finish.
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: Starting no more jobs. Waiting for 1 jobs to finish.
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: Starting no more jobs. Waiting for 3 jobs to finish.
+parallel: This job succeeded:
+sleep 1; exit 0
+parallel: Starting no more jobs. Waiting for 2 jobs to finish.
 0
 ### testhalt --halt soon,success=1
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: Starting no more jobs. Waiting for 3 jobs to finish.
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: Starting no more jobs. Waiting for 2 jobs to finish.
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: Starting no more jobs. Waiting for 1 jobs to finish.
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: Starting no more jobs. Waiting for 3 jobs to finish.
+parallel: This job succeeded:
+sleep 1; exit 0
+parallel: Starting no more jobs. Waiting for 2 jobs to finish.
 0
 ### testhalt --halt soon,success=2
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: Starting no more jobs. Waiting for 3 jobs to finish.
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: Starting no more jobs. Waiting for 2 jobs to finish.
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: Starting no more jobs. Waiting for 1 jobs to finish.
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: Starting no more jobs. Waiting for 3 jobs to finish.
+parallel: This job succeeded:
+sleep 1; exit 0
+parallel: Starting no more jobs. Waiting for 2 jobs to finish.
 0
 ### testhalt --halt soon,success=30%
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: Starting no more jobs. Waiting for 3 jobs to finish.
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: Starting no more jobs. Waiting for 2 jobs to finish.
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: Starting no more jobs. Waiting for 1 jobs to finish.
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: Starting no more jobs. Waiting for 3 jobs to finish.
+parallel: This job succeeded:
+sleep 1; exit 0
+parallel: Starting no more jobs. Waiting for 2 jobs to finish.
+parallel: This job succeeded:
+sleep 1; exit 0
+parallel: Starting no more jobs. Waiting for 1 jobs to finish.
+parallel: This job succeeded:
+sleep 1; exit 0
 0
 ### testhalt --halt now,success=70%
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 50
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 parallel: This job succeeded:
-sleep 0; exit 0
+sleep 1; exit 0
 50
 echo '**'
 **
